// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dns from "node:dns";
// Many clouds resolve IPv6 first; Supabase/Railway paths sometimes fail with P1001 otherwise.
dns.setDefaultResultOrder("ipv4first");

import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePostgresDatabaseUrl } from "./src/config/normalizeDatabaseUrl.js";

if (process.env.DATABASE_URL) {
  process.env.DATABASE_URL = normalizePostgresDatabaseUrl(process.env.DATABASE_URL);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
